import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:chataway_plus/core/responsive_layout/responsive_layout_builder.dart';
import 'package:chataway_plus/core/connectivity/connectivity_service.dart';
import 'package:chataway_plus/features/voice_call/data/models/call_model.dart';
import 'package:chataway_plus/features/voice_call/data/services/call_signaling_service.dart';
import 'package:chataway_plus/features/voice_call/presentation/providers/call_provider.dart';
import 'package:chataway_plus/features/voice_call/presentation/widgets/call_avatar.dart';
import 'package:chataway_plus/features/voice_call/presentation/widgets/call_action_button.dart';
import 'package:chataway_plus/features/voice_call/presentation/pages/active_call_page.dart';
import 'package:chataway_plus/features/voice_call/presentation/pages/video_call_page.dart';

/// Outgoing call page — shown to the CALLER after initiating a call
/// WhatsApp-style: Shows "Calling..." → "Ringing..." → transitions to ActiveCallPage
/// Handles: offline, unavailable, rejected, timeout (45s), and accepted scenarios
///
/// IMPORTANT: Back navigation is blocked. User can only cancel via the end-call button.
class OutgoingCallPage extends ConsumerStatefulWidget {
  final String currentUserId; // Current user ID
  final String contactId; // Target user ID
  final String contactName;
  final String? contactProfilePic;
  final CallType callType;
  final String channelName;
  final String callId;

  const OutgoingCallPage({
    super.key,
    required this.currentUserId,
    required this.contactId,
    required this.contactName,
    this.contactProfilePic,
    this.callType = CallType.voice,
    required this.channelName,
    required this.callId,
  });

  @override
  ConsumerState<OutgoingCallPage> createState() => _OutgoingCallPageState();
}

class _OutgoingCallPageState extends ConsumerState<OutgoingCallPage>
    with SingleTickerProviderStateMixin {
  final _signaling = CallSignalingService.instance;
  bool _callAccepted = false;

  late AnimationController _fadeController;
  late Animation<double> _fadeAnimation;

  String _callStatus = 'Calling...';
  bool _isEnded = false;
  Timer? _ringTimeoutTimer;

  // Stream subscriptions
  StreamSubscription? _ringSub;
  StreamSubscription? _acceptSub;
  StreamSubscription? _rejectSub;
  StreamSubscription? _endSub;
  StreamSubscription? _unavailableSub;
  StreamSubscription? _errorSub;
  StreamSubscription? _missedSub;

  /// Ring timeout — 45 seconds (generous to account for network delays)
  static const Duration _ringTimeout = Duration(seconds: 45);

  @override
  void initState() {
    super.initState();
    _fadeController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 500),
    );
    _fadeAnimation = CurvedAnimation(
      parent: _fadeController,
      curve: Curves.easeOut,
    );
    _fadeController.forward();

    _startCall();
  }

  void _startCall() {
    // Check connectivity first
    if (!ConnectivityCache.instance.isOnline) {
      setState(() => _callStatus = 'No internet connection');
      _scheduleAutoClose(CallStatus.failed);
      return;
    }

    // Register outgoing call in provider — this ALSO sends the call:initiate
    // signal to the server via CallSignalingService. Do NOT call
    // _signaling.initiateCall separately or the signal fires twice with
    // different channelNames, causing caller/callee to join different
    // Agora channels ("Connection failed" on both screens).
    //
    // IMPORTANT: channelName is generated by the UI (one_to_one_chat_page
    // or chat_list_page) as 'chan_$callId' and passed here. The provider
    // forwards it verbatim to the server — NO re-generation.
    ref
        .read(callProvider)
        .initiateCall(
          callId: widget.callId,
          channelName: widget.channelName,
          contactId: widget.contactId,
          contactName: widget.contactName,
          contactProfilePic: widget.contactProfilePic,
          callType: widget.callType,
        );

    // Listen for signaling events
    _ringSub = _signaling.callRingingStream.listen((data) {
      final callId = data['callId'] ?? '';
      if (callId == widget.callId && mounted) {
        setState(() => _callStatus = 'Ringing...');
      }
    });

    _acceptSub = _signaling.callAcceptedStream.listen((data) {
      final callId = data['callId'] ?? '';
      debugPrint(
        '📞 OutgoingCall: call:accepted received: callId=$callId, widgetCallId=${widget.callId}',
      );
      if (callId == widget.callId && mounted && !_isEnded) {
        debugPrint(
          '📞 OutgoingCall: Transitioning to ActiveCallPage',
        );
        _onCallAccepted();
      }
    });

    _rejectSub = _signaling.callRejectedStream.listen((callId) {
      if (callId == widget.callId && mounted) {
        setState(() => _callStatus = 'Call declined');
        _scheduleAutoClose(CallStatus.rejected);
      }
    });

    _endSub = _signaling.callEndedStream.listen((callId) {
      if (callId == widget.callId && mounted) {
        setState(() => _callStatus = 'Call ended');
        _scheduleAutoClose(CallStatus.ended);
      }
    });

    _unavailableSub = _signaling.callUnavailableStream.listen((callId) {
      if (callId == widget.callId && mounted) {
        setState(() => _callStatus = 'Unavailable');
        _scheduleAutoClose(CallStatus.failed);
      }
    });

    _errorSub = _signaling.callErrorStream.listen((message) {
      if (mounted && !_isEnded) {
        setState(() => _callStatus = message);
        _scheduleAutoClose(CallStatus.failed);
      }
    });

    _missedSub = _signaling.callMissedStream.listen((callId) {
      if (callId == widget.callId && mounted) {
        setState(() => _callStatus = 'No answer');
        _scheduleAutoClose(CallStatus.missed);
      }
    });

    // NOTE: Do NOT call _signaling.initiateCall here — callProvider.initiateCall
    // already sent the signal above. Calling it again would send a duplicate
    // with widget.channelName which may differ from the provider's channelName.

    // Do NOT pre-join Agora channel here.
    // The ActiveCallPage / VideoCallPage will handle joining fresh.
    // Pre-joining here was causing stale engine issues on subsequent calls.

    // Start ring timeout
    _ringTimeoutTimer = Timer(_ringTimeout, () {
      if (!_isEnded && mounted) {
        debugPrint(
          '⏰ OutgoingCall: Ring timeout after ${_ringTimeout.inSeconds}s',
        );
        setState(() => _callStatus = 'No answer');
        _signaling.endActiveCall(
          callId: widget.callId,
          otherUserId: widget.contactId,
        );
        _scheduleAutoClose(CallStatus.missed);
      }
    });
  }

  void _onCallAccepted() {
    if (_isEnded || _callAccepted) return;
    _ringTimeoutTimer?.cancel();
    _isEnded = true;
    _callAccepted = true;

    // Mark call active for correct duration tracking
    ref.read(callProvider).acceptCall();

    // Transition to active call page (voice or video)
    // Use the SAME channelName that was passed to the server — no re-derivation
    final Widget callPage = widget.callType == CallType.video
        ? VideoCallPage(
            currentUserId: widget.currentUserId,
            contactName: widget.contactName,
            contactProfilePic: widget.contactProfilePic,
            channelName: widget.channelName,
            callId: widget.callId,
            otherUserId: widget.contactId,
          )
        : ActiveCallPage(
            currentUserId: widget.currentUserId,
            contactName: widget.contactName,
            contactProfilePic: widget.contactProfilePic,
            callType: widget.callType,
            channelName: widget.channelName,
            callId: widget.callId,
            otherUserId: widget.contactId,
          );

    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted) {
        Navigator.of(context).pushReplacement(
          PageRouteBuilder(
            pageBuilder: (context, animation, secondaryAnimation) => callPage,
            transitionsBuilder: (context, animation, secondaryAnimation, child) {
              return FadeTransition(opacity: animation, child: child);
            },
            transitionDuration: const Duration(milliseconds: 300),
          ),
        );
      }
    });
  }

  void _scheduleAutoClose(CallStatus status) {
    if (_isEnded) return;
    _isEnded = true;
    _ringTimeoutTimer?.cancel();
    ref.read(callProvider).endCallWithStatus(status);
    Future.delayed(const Duration(seconds: 2), () {
      if (mounted) Navigator.of(context).pop();
    });
  }

  void _cancelCall() {
    if (_isEnded) return;
    _isEnded = true;
    _ringTimeoutTimer?.cancel();

    _signaling.endActiveCall(
      callId: widget.callId,
      otherUserId: widget.contactId,
    );
    ref.read(callProvider).endCallWithStatus(CallStatus.ended);
    Navigator.of(context).pop();
  }

  @override
  void dispose() {
    _ringTimeoutTimer?.cancel();
    _fadeController.dispose();
    _ringSub?.cancel();
    _acceptSub?.cancel();
    _rejectSub?.cancel();
    _endSub?.cancel();
    _unavailableSub?.cancel();
    _errorSub?.cancel();
    _missedSub?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ResponsiveLayoutBuilder(
      builder: (context, constraints, breakpoint) {
        final responsive = ResponsiveSize(
          context: context,
          constraints: constraints,
          breakpoint: breakpoint,
        );

        return PopScope(
          canPop: false,
          onPopInvokedWithResult: (didPop, result) {
            if (!didPop) _cancelCall();
          },
          child: Scaffold(
            resizeToAvoidBottomInset: false,
            body: Container(
              width: double.infinity,
              height: double.infinity,
              decoration: const BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                  colors: [
                    Color(0xFF0F172A),
                    Color(0xFF1E293B),
                    Color(0xFF0F172A),
                  ],
                ),
              ),
              child: SafeArea(
                child: SingleChildScrollView(
                  physics: const ClampingScrollPhysics(),
                  child: ConstrainedBox(
                    constraints: BoxConstraints(
                      minHeight: constraints.maxHeight - MediaQuery.of(context).padding.top - MediaQuery.of(context).padding.bottom,
                    ),
                    child: FadeTransition(
                      opacity: _fadeAnimation,
                      child: Column(
                        children: [
                          SizedBox(height: responsive.spacing(16)),
                          // Top bar — call type indicator only, no back button
                          _buildTopBar(responsive),
                          SizedBox(height: responsive.spacing(60)),
                          // Encrypted label
                          _buildEncryptedLabel(responsive),
                          SizedBox(height: responsive.spacing(40)),
                          // Avatar with ripple animation
                          CallAvatar(
                            name: widget.contactName,
                            profilePicUrl: widget.contactProfilePic,
                            size: 120,
                            showRipple: !_isEnded,
                          ),
                          SizedBox(height: responsive.spacing(30)),
                          // Contact name
                          Text(
                            widget.contactName,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: responsive.size(28),
                              fontWeight: FontWeight.bold,
                              letterSpacing: 0.5,
                            ),
                          ),
                          SizedBox(height: responsive.spacing(12)),
                          // Call status
                          _buildCallStatus(responsive),
                          SizedBox(height: responsive.spacing(80)),
                          // End call button — the ONLY way to exit
                          if (!_isEnded) ...[
                            EndCallButton(onTap: _cancelCall),
                            SizedBox(height: responsive.spacing(12)),
                            Text(
                              'Cancel',
                              style: TextStyle(
                                color: Colors.white.withValues(alpha: 0.6),
                                fontSize: responsive.size(13),
                                fontWeight: FontWeight.w500,
                              ),
                            ),
                          ],
                          SizedBox(height: responsive.spacing(40)),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        );
      },
    );
  }

  Widget _buildTopBar(ResponsiveSize responsive) {
    return Padding(
      padding: EdgeInsets.symmetric(horizontal: responsive.spacing(16)),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          // Call type indicator
          Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(
                widget.callType == CallType.video
                    ? Icons.videocam_rounded
                    : Icons.call_rounded,
                color: Colors.white.withValues(alpha: 0.5),
                size: responsive.size(16),
              ),
              SizedBox(width: responsive.spacing(6)),
              Text(
                widget.callType == CallType.video ? 'Video Call' : 'Voice Call',
                style: TextStyle(
                  color: Colors.white.withValues(alpha: 0.5),
                  fontSize: responsive.size(13),
                  fontWeight: FontWeight.w500,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildEncryptedLabel(ResponsiveSize responsive) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Icon(
          Icons.lock_rounded,
          color: Colors.white.withValues(alpha: 0.4),
          size: responsive.size(14),
        ),
        SizedBox(width: responsive.spacing(6)),
        Text(
          'End-to-end encrypted',
          style: TextStyle(
            color: Colors.white.withValues(alpha: 0.4),
            fontSize: responsive.size(12),
            fontWeight: FontWeight.w500,
          ),
        ),
      ],
    );
  }

  Widget _buildCallStatus(ResponsiveSize responsive) {
    final isError =
        _callStatus == 'Unavailable' ||
        _callStatus == 'Call declined' ||
        _callStatus == 'No answer' ||
        _callStatus == 'No internet connection' ||
        _callStatus == 'Call ended';

    final isRinging = _callStatus == 'Ringing...';

    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        if (!_isEnded && !isError)
          Padding(
            padding: EdgeInsets.only(right: responsive.spacing(8)),
            child: SizedBox(
              width: responsive.size(14),
              height: responsive.size(14),
              child: CircularProgressIndicator(
                strokeWidth: 2,
                valueColor: AlwaysStoppedAnimation<Color>(
                  Colors.white.withValues(alpha: 0.5),
                ),
              ),
            ),
          ),
        if (isError)
          Padding(
            padding: EdgeInsets.only(right: responsive.spacing(8)),
            child: Icon(
              Icons.call_end_rounded,
              color: const Color(0xFFEF4444),
              size: responsive.size(18),
            ),
          ),
        if (isRinging)
          Padding(
            padding: EdgeInsets.only(right: responsive.spacing(8)),
            child: Icon(
              Icons.ring_volume_rounded,
              color: const Color(0xFF22C55E),
              size: responsive.size(18),
            ),
          ),
        Text(
          _callStatus,
          style: TextStyle(
            color: isError
                ? const Color(0xFFEF4444).withValues(alpha: 0.8)
                : isRinging
                ? const Color(0xFF22C55E)
                : Colors.white.withValues(alpha: 0.6),
            fontSize: responsive.size(16),
            fontWeight: isRinging ? FontWeight.w600 : FontWeight.w400,
          ),
        ),
      ],
    );
  }
}
